version: "3.7"

networks:
  message_broker:
    driver: overlay
  
services:
  rabbitmq:
    image: rabbitmq:4.0-alpine
    ports:
      - '5672:5672'
    volumes:
      - type: bind
        source: ./dados
        target: /var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234

  web:
    build:
      context: .
      dockerfile: ./scripts/dockerfiles/site
    depends_on:
      - rabbitmq